# Generated by Django 3.0.7 on 2020-06-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privatefileuploaded', models.FileField(upload_to='privatefiles/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Fileupload',
        ),
    ]
