# Generated by Django 3.0.7 on 2020-06-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0003_publicfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfileupload',
            name='publicfileuploaded',
            field=models.FileField(upload_to='privatefiles/%Y/%m/%d'),
        ),
    ]
