# Generated by Django 3.0.7 on 2020-06-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0004_auto_20200615_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfileupload',
            name='publicfileuploaded',
            field=models.FileField(upload_to='publicfiles/%Y/%m/%d'),
        ),
    ]
